package plantenApp;

import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.image.ImageView;

public class ControllerOverzicht {
    public ImageView ivHabitusDetailO;
    public ImageView ivBladDetailO;
    public ImageView ivBloeiDetailO;
    public ListView lvFrequentieO;
    public ListView lvBeheerbehandelingO;
    public Label lblTypeO;
    public Label lblFamilieO;
    public Label lblGeslachtO;
    public Label lblSoortO;
    public Label lblVariantO;
    public Label lblOntwikkelingssnelheidO;
    public CheckBox rbSociabiliteit1O;
    public CheckBox rbSociabiliteit2O;
    public CheckBox rbSociabiliteit3O;
    public CheckBox rbSociabiliteit5O;
    public CheckBox rbSociabiliteit4O;
    public Label lblStrategieO;
    public Label lblLevensduurO;
    public Label lblXO;
    public Label lblYO;
    public Label lblBezonningO;
    public Label lblVochtbehoefteO;
    public Label lblVoedingsbehoefteO;
    public Label lblReactieO;
    public Label lblGrondsoortO;
    public ListView lvHabitatO;
    public Label lblNectarwaardeO;
    public Label lblPollenwaardeO;
    public Label lblBijvriendelijkO;
    public Label lblVlindervriendelijkO;
    public Label lblEetbaarO;
    public Label lblKruidgebruikO;
    public Label lblGeurendO;
    public Label lblVorstgevoeligO;
    public Label lblHabitusO;
    public ImageView ivHabitusO;
    public Label lblBladgrootteO;
    public Label lblBladvormO;
    public Label lblRatioO;
    public Label lblSpruitfenologieO;
    public Label lblLevensvormO;
    public Label lblBloeiwijzeO;
    public ImageView ivBloeiwijzeO;
    public Label bladhoogteMaxJanO;
    public Label bladkleurJanO;
    public Label bladkleurFebO;
    public Label bladkleurMaaO;
    public Label bladkleurAprO;
    public Label bladkleurMeiO;
    public Label bladkleurJunO;
    public Label bladkleurJulO;
    public Label bladkleurAugO;
    public Label bladkleurSeptO;
    public Label bladkleurOktO;
    public Label bladkleurNovO;
    public Label bladkleurDecO;
    public Label bloeihoogteMinJanO;
    public Label bloeihoogteMinFebO;
    public Label bloeihoogteMinMaartO;
    public Label bloeihoogteMinAprilO;
    public Label bloeihoogteMinMeiO;
    public Label bloeihoogteMinJunO;
    public Label bloeihoogteMinJulO;
    public Label bloeihoogteMinAugO;
    public Label bloeihoogteMinSeptO;
    public Label bloeihoogteMinOktO;
    public Label bloeihoogteMinNovO;
    public Label bloeihoogteMinDecO;
    public Label bloeihoogteMaxJanO;
    public Label bloeihoogteMaxFebO;
    public Label bloeihoogteMaxMaartO;
    public Label bloeihoogteMaxAprO;
    public Label bloeihoogteMaxMeiO;
    public Label bloeihoogteMaxJunO;
    public Label bloeihoogteMaxJulO;
    public Label bloeihoogteMaxAugO;
    public Label bloeihoogteMaxSeptO;
    public Label bloeihoogteMaxOktO;
    public Label bloeihoogteMaxNovO;
    public Label bloeihoogteMaxDecO;
    public Label bloeikleurJanO;
    public Label bloeikleurFebO;
    public Label bloeikleurMaartO;
    public Label bloeikleurAprilO;
    public Label bloeikleurMeiO;
    public Label bloeikleurJunO;
    public Label bloeikleurJuliO;
    public Label bloeikleurAugO;
    public Label bloeikleurSeptO;
    public Label bloeikleurOktO;
    public Label bloeikleurNovO;
    public Label bloeikleurDecO;


}
